/* Autogenerated file - please do not edit. */
#include "devices.h"

htc_device_t htc_devices[] = {
    { "cp2dtg", "HTC One ST", 0 },
    { "cp2dug", "HTC One SU", 1 },
    { "cp3dug", "HTC Desire 600 - China Unicom", 2 },
    { "deluxe_j", "HTC J Butterfly", 3 },
    { "deluxe_u", "HTC J DNA", 4 },
    { "deluxe_ub1", "HTC Butterfly", 5 },
    { "endeavor_td", "HTC One XT", 6 },
    { "endeavor_u", "HTC One X (T3)", 7 },
    { "enrc2_u", "HTC One X+", 8 },
    { "enrc2b_u", "HTC One X+", 9 },
    { "evita", "HTC One X (S4)", 10 },
    { "evitare_ul", "HTC One X+ LTE", 11 },
    { "fireball", "HTC Incredible 4G LTE", 12 },
    { "jel_dd", "HTC One XC", 13 },
    { "jewel", "HTC Evo 4G LTE", 14 },
    { "k2_plc_cl", "HTC One SV", 15 },
    { "k2_u", "HTC One SV", 16 },
    { "k2_ul", "HTC One SV", 17 },
    { "m7_u", "HTC One U", 18 },
    { "m7_ul", "HTC One UL", 19 },
    { "m7_wls", "HTC One WLS", 20 },
    { "m7cdtu", "HTC One - China Mobile", 21 },
    { "m7cdug", "HTC One - China Unicom", 22 },
    { "m7cdwg", "HTC One - China Telecom", 23 },
    { "magnids", "HTC Desire SV", 24 },
    { "monarudo", "HTC Droid DNA", 25 },
    { "mystul", "HTC First", 26 },
    { "proto", "HTC Desire X", 27 },
    { "protodug", "HTC Desire V", 28 },
    { "prototd", "HTC T329t", 29 },
    { "tc2", "HTC One VX", 30 },
    { "ville", "HTC One S", 31 },
    { "villec2", "HTC One S C2", 32 },
    { 0, 0, 0 }
};

htc_device_t *htc_get_devices() 
{
    return htc_devices;
}