/* Autogenerated file - please do not edit. */
#include "devices.h"

htc_device_t htc_devices[] = {
    { "endeavor_td", "HTC One XT", 0 },
    { "endeavor_u", "HTC One X (T3)", 1 },
    { "era_u", "HTC One X+", 2 },
    { "evita", "HTC One X (S4)", 3 },
    { "fireball", "HTC Incredible 4G LTE", 4 },
    { "jel_dd", "HTC X720", 5 },
    { "jewel", "HTC Evo 4G LTE", 6 },
    { "ville", "HTC One S", 7 },
    { 0, 0, 0 }
};

htc_device_t *htc_get_devices() 
{
    return htc_devices;
}