/* Autogenerated file - please do not edit. */
#include "devices.h"

htc_device_t htc_devices[] = {
    { "cp2dcg", "HTC One SC", 0 },
    { "cp2dtg", "HTC One ST", 1 },
    { "cp2dug", "HTC One SU", 2 },
    { "cp3dug", "HTC Desire 600 - China Unicom", 3 },
    { "deluxe_j", "HTC J Butterfly", 4 },
    { "deluxe_u", "HTC J DNA", 5 },
    { "deluxe_ub1", "HTC Butterfly", 6 },
    { "dlxp_u", "HTC Butterfly S", 7 },
    { "dlxp_ul", "HTC Butterfly S LTE", 8 },
    { "endeavor_td", "HTC One XT", 9 },
    { "endeavor_u", "HTC One X (T3)", 10 },
    { "enrc2_u", "HTC One X+", 11 },
    { "enrc2b_u", "HTC One X+", 12 },
    { "evita", "HTC One X (S4)", 13 },
    { "evitare_ul", "HTC One X+ LTE", 14 },
    { "fireball", "HTC Incredible 4G LTE", 15 },
    { "jel_dd", "HTC One XC", 16 },
    { "jewel", "HTC Evo 4G LTE", 17 },
    { "k2_plc_cl", "HTC One SV", 18 },
    { "k2_u", "HTC One SV", 19 },
    { "k2_ul", "HTC One SV", 20 },
    { "m4_u", "HTC One Mini U", 21 },
    { "m4_ul", "HTC One Mini UL", 22 },
    { "m7_u", "HTC One U", 23 },
    { "m7_ul", "HTC One UL", 24 },
    { "m7_wlj", "HTC One WLJ", 25 },
    { "m7_wls", "HTC One WLS", 26 },
    { "m7_wlv", "HTC One WLV", 27 },
    { "m7cdtu", "HTC One - China Mobile", 28 },
    { "m7cdug", "HTC One - China Unicom", 29 },
    { "m7cdwg", "HTC One - China Telecom", 30 },
    { "magnids", "HTC Desire SV", 31 },
    { "monarudo", "HTC Droid DNA", 32 },
    { "mystul", "HTC First", 33 },
    { "proto", "HTC Desire X", 34 },
    { "protodug", "HTC Desire V", 35 },
    { "prototd", "HTC T329t", 36 },
    { "tc2", "HTC One VX", 37 },
    { "ville", "HTC One S", 38 },
    { "villec2", "HTC One S C2", 39 },
    { 0, 0, 0 }
};

htc_device_t *htc_get_devices() 
{
    return htc_devices;
}